//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projectmigration5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Product_id { get; set; }
        public string ProductName { get; set; }
        public string ProductDescr { get; set; }
        public int Price { get; set; }
        public string ImageFile { get; set; }
        public Nullable<bool> isFeatured { get; set; }
    }
}
